### ISSUE TITLE
Very poor performance ?!

### ISSUE THREAD

**Issue by eratical** [AcuGIS/OpenTileServer#16]
I can't see what I have done wrong, executed the script with:

`./opentileserver.sh web carto http://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf
`
After it has finished the tiles are working but verrrrrryyyyy slow, it takes 2 Minutes to render, sometimes it fails to render tiles and a pink tile is shown. In this moment the cpu goes up to 100%, takes some time and then it shows the tiles that were pink before. It's a very very poor performance, but I don't see whats wrong ?!

Have tried it on several different VMs, Core-I7, 16GB Ram, fresh Install of Ubuntu 14.04 etc. Nothing seem to help :-(

**Comment by DavidGhedini** [comment]
Are you using SSD?

**Comment by eratical** [comment]
My first try was on a machine with ssd, but same behaviour

**Comment by DavidGhedini** [comment]
For a PBF that size, 16 GB of RAM with SSD should run just fine.  Is you PostgreSQL database tuned to match your hardware?

**Comment by eratical** [comment]
No, i have just started the script.
I can not image that just a config for PostgreSQL will do the trick :-/

**Comment by eratical** [comment]
http://195.x.y.z
That's the Server, I only used a part of Germany (NRW) and it still is really slow.
The first 6-7 Zoom-Level are fine because they are rendered but the rest is slow

Edit: removed the ip, i give it up :-(

**Comment by DavidGhedini** [comment]
I haven't had anyone else raise performance issues.  
1. Tuning PostgreSQL **is** a big deal because that is how the tiles are being served.  
2. Because it is all I/O-database process you need SSD and plenty of RAM
The size of the PBF, with 16 GB of RAM and SSD should run very well and very fast.
You need to look at your hardware and see where the bottleneck is.  You also need to tune your PostgreSQL database to match the hardware resources.
